- dmoj/checkers/__init__.py
- dmoj/checkers/identical.py
Adds new identical checker that returns true only when output is **exactly** the same as the answer.
> Identical checker

- dmoj/executors/RUST.py
Adds a couple nice things for Rust. [More details here.](https://github.com/DMOJ/dmoj-rust/pull/1)
> Add dmoj crate for Rust submissions

- dmoj/executors/RUST.py
Oops, missed an important part of the puzzle in #261. 😅
> Actually add dmoj crate

- .travis.yml
As suggested in https://docs.travis-ci.com/user/caching/#Rust-Cargo-cache.
> Cache cargo packages

- dmoj/executors/gcc_executor.py
- dmoj/graders/signature.py
Assuming I haven't had too many mushrooms, this should work.
> Implement #225

- dmoj/executors/java_executor.py
Please accept DMOJ/judge-testsuite#9 first
> Attempt to fix #90

- dmoj/generator.py
> Get generator to work with JAVA and RUBY

- dmoj/executors/autoconfig.py
> Allow for silent mode

- dmoj/graders/__init__.py
- dmoj/graders/interactive.py
Writing your own interactor can be painful, and this should remove most of the pain.
> Create Interactive Grader

- dmoj/judgeenv.py
Branch `rec` has errors, using this instead.
@Xyene @quantum5 plz delete `rec`. Ty
> Implement #82

- dmoj/cptbox/sandbox.py
- dmoj/graders/standard.py
> Extend Protection Fault Tuple

- dmoj/checkers/linecount.py
- Move extraneous output check to the beginning
- Handle pretests correctly
> Generalize line comparison of linecount.py

- dmoj/cptbox/sandbox.py
- dmoj/executors/VC.py
- dmoj/executors/base_executor.py
- dmoj/executors/gcc_executor.py
- dmoj/executors/mixins.py
- dmoj/graders/standard.py
- dmoj/utils/__init__.py
> Use LD_PRELOAD and nobuf.so to disable output buffering for libc languages

- dmoj/cptbox/_cptbox.pyx
- dmoj/cptbox/helper.cpp
> Address PTRACE_TRACEME potential failure

- dmoj/executors/MONOCS.py
> Prefer `mcs` over `dmcs`

- dmoj/executors/BF.py
> Make Brainfuck cell count scale with memory limit

- dmoj/cptbox/chroot.py
- dmoj/executors/gcc_executor.py
- dmoj/executors/mixins.py
- dmoj/executors/mono_executor.py
- dmoj/graders/standard.py
- dmoj/judge.py
- dmoj/problem.py
**NOT TO BE MERGED** until all problems on dmoj.ca are updated to not rely on `io_redirects`.
> Remove IO redirects in favour of IO symlinks

- dmoj/problem.py
> Handle data missing trailing newline normalization

- dmoj/judge.py
- dmoj/judgeenv.py
- dmoj/utils/pyyaml_patch.py
> Support Unicode judge names

- .travis.test.py
- .travis.yml
- dmoj/executors/DART.py
- dmoj/executors/base_executor.py
- dmoj/judgeenv.py
> Using xenial image on Travis

- dmoj/executors/mono_executor.py
> Make mono_executor.py PY3 compliant

- dmoj/checkers/_checker.c
- dmoj/tests/test_checker.py
>  Fix standard checker ignoring whitespace under some situations 

- dmoj/executors/GO.py
> GO: compile original source code; #450

- .gitignore
- dmoj/cptbox/_cptbox.pyx
- dmoj/cptbox/chroot.py
- dmoj/cptbox/handlers.py
- dmoj/cptbox/helper.cpp
- dmoj/cptbox/helper.h
- dmoj/cptbox/sandbox.py
- dmoj/executors/COFFEE.py
- dmoj/executors/DART.py
- dmoj/executors/PIKE.py
- dmoj/executors/PYPY.py
- dmoj/executors/PYPY3.py
- dmoj/executors/RUBY2.py
- dmoj/executors/java_executor.py
- dmoj/executors/mixins.py
- dmoj/executors/mono_executor.py
This PR aims to remove the hacks powering the Mono executor, in light of the more robust cptbox defaults.
> Simplify Mono executor

- .travis.test.py
- .travis.yml
- dmoj/executors/RKT.py
Fixes #469.
Also adds Racket to Travis.
> Give Racket a `data_grace`

- dmoj/judge.py
- dmoj/packet.py
This PR removes old, half-finished custom invocation code. It is both poorly written _and_ unused, so it needs to go.
> Remove half-baked custom invocation code

- dmoj/executors/gcc_executor.py
> Pass `-fmax-errors=N` to GCC/Clang; #471

- dmoj/graders/standard.py
- dmoj/problem.py
- dmoj/result.py
> Show generator stderr in case of non-zero return code

- dmoj/executors/base_executor.py
- dmoj/executors/java_executor.py
- dmoj/generator.py
- dmoj/graders/base.py
- dmoj/graders/custom.py
- dmoj/graders/signature.py
- dmoj/graders/standard.py
- dmoj/judge.py
- dmoj/packet.py
- dmoj/problem.py
This coincidentally also fixes #467, as well as some of the `KeyError` issues reported on the site.
> Decouple packet manager from graders + other cleanups

- dmoj/citest.py
- dmoj/cli.py
- dmoj/commands/base_command.py
- dmoj/commands/submissions.py
- dmoj/executors/asm_executor.py
- dmoj/executors/autoconfig.py
- dmoj/executors/base_executor.py
- dmoj/judge.py
- dmoj/monitor.py
- dmoj/testsuite.py
- dmoj/utils/ansi.py
- requirements.txt
- setup.py
Addresses #478.
Should not be merged until the appropriate site-side change is made.
> Move ANSI HTML-ifying to the site

- .github/workflows/update-syscalls.yml
This includes the lessons learned in setting up the site's i18n workflows.
> Make syscall updating workflow more robust

- dmoj/executors/asm_executor.py
Mixins now inherit from ASMExecutor to appease mypy.
> Resolve mypy errors in asm_executor.py

- dmoj/checkers/linecount.py
- dmoj/checkers/sorted.py
- dmoj/checkers/standard.py
- dmoj/utils/unicode.py
> Fix mypy in checkers

- dmoj/tests/test_malformed_unicode.py
- dmoj/tests/test_problem.py
> Replace assertRaisesRegexp with assertRaisesRegex; #337

- dmoj/cptbox/isolate.py
- dmoj/executors/RUBY2.py
- dmoj/executors/SWIFT.py
These were part of the now-defunct `travis-bionic` branch.
> Misc executor fixes

- dmoj/checkers/__init__.py
- dmoj/checkers/bridged.py
- dmoj/generator.py
- dmoj/graders/standard.py
- dmoj/utils/aux_files.py
Replaces the more ad-hoc `testlib` checkers with a checker module.
> Add bridged checker

- dmoj/executors/python_executor.py
Before patch:
```
dmoj> rejudge 1
Start grading helloworld/2 in PY2...
Test case  1 AC [0.034s (0.052s) | 6320kb]
Done grading helloworld/2.
dmoj> rejudge 1
Start grading helloworld/2 in PY2...
Test case  1 AC [0.038s (0.052s) | 6320kb]
Done grading helloworld/2.
dmoj> rejudge 1
Start grading helloworld/2 in PY2...
Test case  1 AC [0.043s (0.052s) | 6320kb]
Done grading helloworld/2.
dmoj> rejudge 1
Start grading helloworld/2 in PY2...
Test case  1 AC [0.038s (0.051s) | 6320kb]
Done grading helloworld/2.
```
After patch:
```
dmoj> rejudge 1
Start grading helloworld/2 in PY2...
Test case  1 AC [0.014s (0.024s) | 6320kb]
Done grading helloworld/2.
dmoj> rejudge 1
Start grading helloworld/2 in PY2...
Test case  1 AC [0.014s (0.023s) | 6320kb]
Done grading helloworld/2.
dmoj> rejudge 1
Start …
```
> Use py_compile in Python executor

- dmoj/executors/java_executor.py
"Newer" (post-Java 8) JVMs regressed a bit in terms of handling out-of-memory situations during
initialization, whereby they now dump a crash log rather than exiting with
java.lang.OutOfMemoryError. Handle this case so that we don't erroneously emit internal errors.
> java: handle new failure mode for JVM MLE

- dmoj/cptbox/tracer.py
- dmoj/graders/bridged.py
Hopefully fixes bridged interactor race conditions.
> Make TracedPopen launch synchronous

- dmoj/cptbox/tracer.py
> Adjust OOM score for submissions

- .docker.test.py
- README.md
- dmoj/executors/ZIG.py
Not sure what else CI runs, but I ran `.docker.test.py` and AC
﻿
> Add executor for zig

- .docker/entry
> Run Docker judge with jemalloc

- dmoj/executors/CBL.py
> CBL: detect new capitalization formats for error/note/warning

- .docker.test.py
- .docker/entry
- dmoj/cli.py
- dmoj/commands/rejudge.py
- dmoj/commands/resubmit.py
- dmoj/commands/submit.py
- dmoj/cptbox/_cptbox.pyx
- dmoj/cptbox/helper.cpp
- dmoj/graders/base.py
- dmoj/judge.py
- dmoj/packet.py
- dmoj/problem.py
- dmoj/testsuite.py
> Spawn a separate judge process to deal with each submission

- dmoj/cptbox/tracer.py
> cptbox: don't attempt to kill dead processes

- .travis.yml
This should fix issues with codecov not updating.
For proof that it works, see https://codecov.io/gh/DMOJ/judge-server/commit/cf9d866bf9310cbdd9786032363c54e25608818b.
> Switch codecov bash uploader

- .docker/entry
This reverts commit ae73a48defdda19a54a9997db07014eb9f274962.
> Revert "Stop using jemalloc in Docker"

- dmoj/cptbox/helper.cpp
> cptbox: fix spurious seccomp initialization failures

- dmoj/contrib/coci.py
- dmoj/contrib/testlib.py
(Tested against https://github.com/DMOJ/judge-testsuite/pull/58)
> Allow extra stderr output from COCI and testlib checkers

- dmoj/executors/base_executor.py
- dmoj/executors/compiled_executor.py
- dmoj/executors/gcc_executor.py
- dmoj/graders/signature.py
- dmoj/utils/helper_files.py
This should make executors picklable.
> Remove new executor class creation hack

- dmoj/judge.py
- dmoj/packet.py
> judge: don't abort if nothing is running

- dmoj/executors/RUST.py
> RUST: strip binaries to lower memory overhead

- dmoj/graders/signature.py
> Signature grade in submitted language

- dmoj/packet.py
> packet: totally quit on network error

- .docker/tier1/Dockerfile
- .docker/tier2/Dockerfile
- .docker/tier3/Dockerfile
- README.md
- setup.py
Hopefully that's the last of them...
> Change URL from `judge` to `judge-server`

- dmoj/judge.py
Refs #720; less verbose implementation.
> judge: properly report errors without wrapping them

- .github/workflows/build.yml
- .travis.yml
Due to greater parallelization and executor availability of GitHub Actions, this is expected to reduce wait times massively.
> Run amd64 CI tests on GitHub Actions

- dmoj/cptbox/__init__.py
> Remove `NullTracer` implementation

- .github/workflows/build.yml
- .travis.yml
Also only run arm64 tests on Travis.
> Run CI tests on python 3.9

- dmoj/problem.py
> problem: set output length to 0 for siggraded problems

- dmoj/executors/GO.py
Set to 96MB, should I attempt to tighten this bound?
> GO: increase `data_grace`; fixes #756

- dmoj/cptbox/_cptbox.pyx
* Changed language level to Python 3
* Changed property-syntax; fixes #791
> Modernize Cython code

- dmoj/cptbox/_cptbox.pyx
- dmoj/cptbox/helper.cpp
- dmoj/cptbox/helper.h
- dmoj/cptbox/tracer.py
> Turn special cptbox return codes into constants

- dmoj/cptbox/_cptbox.pyx
- dmoj/cptbox/helper.cpp
- dmoj/cptbox/helper.h
- dmoj/cptbox/tracer.py
- dmoj/executors/mixins.py
> Remove support for fds

- dmoj/cptbox/_cptbox.pyx
- dmoj/cptbox/ptbox.h
- dmoj/cptbox/ptdebug_arm.cpp
- dmoj/cptbox/ptdebug_arm64.cpp
- dmoj/cptbox/ptdebug_freebsd_x64.cpp
- dmoj/cptbox/ptdebug_x64.cpp
- dmoj/cptbox/ptdebug_x86.cpp
> Convert syscall setter errors into exceptions

- .github/workflows/update-syscalls.yml
Context: https://github.com/DMOJ/judge-server/actions/runs/449840787. It failed.
See https://github.com/DMOJ/judge-server/actions/runs/450042055 for it in action.
> Make update-syscalls use peter-evans/create-pull-request@v3

- testsuite/seed2/init.yml
We don't want @Xyene gouging his eyes out with a spoon, now do we...
> testsuite: Fix typo in `seed2` `init.yml`

- dmoj/packet.py
Warning: I have not tested this code.
> Do not back off more than a minute; fixes #648

- dmoj/citest.py
- dmoj/commands/__init__.py
- dmoj/commands/problems.py
- dmoj/commands/resubmit.py
- dmoj/commands/submit.py
- dmoj/commands/test.py
- dmoj/judge.py
- dmoj/judgeenv.py
- dmoj/packet.py
- dmoj/problem.py
- dmoj/testsuite.py
- testsuite/coci_partial/tests/py_ac/test.yml
- testsuite/coci_partial/tests/py_garbage_ac/test.yml
- testsuite/coci_partial/tests/py_lower_bound_ac/test.yml
- testsuite/coci_partial/tests/py_upper_bound_ac/test.yml
- testsuite/testlib_partial/tests/py_ac/test.yml
Closes #335. 
Currently looks like:
```
Testing problem helloworld...
Running test A Correct Solution
Start grading helloworld/1 in PY2...
Test case  1 AC [0.038s (0.046s) | 6908kb]
Done grading helloworld/1.
Result of test A Correct Solution: Success
Test complete
All tests passed.
```
> Add problem validation for `dmoj-cli`; #335

- dmoj/checkers/__init__.py
- dmoj/checkers/linematches.py
- dmoj/tests/test_checker.py
There are problems such as https://dmoj.ca/problem/coci09c4p4 that reward a % of points for the test case if the output is partially correct.
> Add checker for problems that reward points based on lines matched

- dmoj/checkers/linecount.py
- dmoj/testsuite.py
- testsuite/linecount/tests/python_echo/test.yml
> checker: Move `linecount` line-by-line feedback to `extended_feedback`

- dmoj/contrib/peg.py
This is more confusing than the goddamn plot of Interstellar, and that
had pop culture 5D nonsense...
> Fix PEG grader format

- dmoj/cptbox/helper.cpp
- dmoj/cptbox/ptdebug.cpp
- dmoj/cptbox/ptproc.cpp
This PR is based on #892 and should be rebased after that one is merged.
> cptbox: fix all compilation warnings

- dmoj/cptbox/helper.cpp
We no longer support kernels older than 4.8 anyway. Also, the ifdef was
never being taken because we failed to include sys/prctl.h...
> cptbox: always set PR_SET_NO_NEW_PRIVS

- dmoj/utils/ansi.py
- dmoj/utils/error.py
- dmoj/utils/helper_files.py
- dmoj/utils/load.py
- dmoj/utils/module.py
- dmoj/utils/os_ext.py
Most just adds `mypy` and switch to f-strings. Also start using `signal.strsignal` instead of `ctypes`.
> Improve dmoj.utils.*

- .docker.test.py
- dmoj/executors/DART.py
- dmoj/executors/PIKE.py
- dmoj/executors/RKT.py
- dmoj/executors/compiled_executor.py
- dmoj/executors/java_executor.py
- dmoj/testsuite.py
- testsuite/helloworld/tests/sandbox_c_bad_unicode_open_noat/test.linux.yml
- testsuite/helloworld/tests/sandbox_c_nametoolong_noat/test.linux.yml
- testsuite/helloworld/tests/sandbox_c_null_path_noat/test.linux.yml
This PR also fixes all the issues that prevent executors from being used on arm64, as well as failing tests.
> ci: fix ARM64 docker test

- dmoj/cptbox/_cptbox.pyi
- dmoj/cptbox/_cptbox.pyx
- dmoj/executors/base_executor.py
- dmoj/judge.py
- dmoj/result.py
> cptbox: track and report context switches

- dmoj/executors/TEXT.py
- dmoj/executors/ZIG.py
- dmoj/executors/mixins.py
Closes #965. Refactored the code into a mixin for future use. ZIG also currently does this.
> cptbox: strip carriage returns in TEXT

- dmoj/packet.py
This changed recently IIRC. We should fix these outdated comments.
> Re-comment logic for new fallback scheme

- dmoj/judge.py
- dmoj/utils/load.py
> Fix `no_implicit_optional` mypy error

- dmoj/executors/RUST.py
Because our list of dependencies grew, so did our compile times. This is a much bigger deal because rust compiles dependencies even if they are unused. See [this submission](https://dmoj.ca/submission/5018534) to Hello, World from myself.
This PR adds an option to make Rust compile into a shared directory, which shares dependencies.
From the perspective of `cargo`, it should seem like we are the same package, changing our source code every time a submission comes in.
> executors/RUST: build rust into shared directory

- dmoj/executors/RUST.py
Closes https://github.com/DMOJ/judge-server/issues/1076.
Merge #1077 first.
> executors/RUST: remove DMOJ_CARGO_OFFLINE

- dmoj/utils/os_ext.py
Rendered unnecessary after #1079.
> Remove `bool_env`

- README.md
- dmoj/executors/LLC.py
```console
$ python -m dmoj.executors -e LLC
Self-testing executors
Self-testing LLC:    Success [0.001s, 512 KB]    llc 11.0.1, ld_x64 2.35.2
```
> Implement LLVM-IR executor LLC

- dmoj/judgeenv.py
- dmoj/monitor.py
- dmoj/tests/test_glob_ext.py
- dmoj/utils/glob_ext.py
Closes #772. Also supersedes #1026.
> Use problem globs to declare problem storage roots

- dmoj/graders/bridged.py
Before this change, the interactor failing to compile was reported in the same way as the user's submission failing to compile.
> Report interactor compile error as internal error

- .docker/entry
- .docker/tier1/Dockerfile
- .docker/tier2/Dockerfile
- .docker/tier3/Dockerfile
> Use a virtualenv in docker image

- .docker/tier1/Dockerfile
- .docker/tier2/Dockerfile
- .docker/tier3/Dockerfile
`runuser` doesn't do the job of an `init` process such as reaping zombies.
> Use a real init process inside docker instead of runuser

- testsuite/helloworld/tests/sandbox_nasm_kill_judge/test.linux.yml
Analog of c06f902e6220cc4a134ac7b21a97b465bb1502cd.
> testsuite/sandbox_nasm_kill_judge: increase memory limit

- .docker.test.py
> Temporarily disable DART in CI

- dmoj/executors/DART.py
- dmoj/executors/HASK.py
See individual commits.
Passing run: https://github.com/DMOJ/runtimes-docker/actions/runs/7439624610
> Fix runtimes-docker build

- dmoj/executors/PY2.py
- dmoj/executors/PY3.py
- dmoj/executors/PYPY.py
- dmoj/executors/PYPY3.py
- dmoj/executors/python_executor.py
> executors/python: add coloring for compileall error messages
