DMOJ/judge-server

dmoj/executors/PY2.py

During self-testing on Ubuntu 16.04, Python 2 would get a segmentation fault. This is the change to fix this.

Add sysinfo to PY2

---

dmoj/executors/RUST.py

Cargo is Rust's package manager. This PR opens the door to linking dependencies like https://github.com/DMOJ/dmoj-rust/.

Compile rust programs with cargo

---

dmoj/executors/RUST.py

Also updates the test program because the `flush!` macro is no longer required (or supported).

Bump minimum dmoj crate dependency

---

dmoj/executors/RUST.py

This allows cargo to bypass hitting the network to determine which dependencies to use.

Include pre-generated Cargo.lock for Rust

---

dmoj/judge.py
dmoj/problem.py

Make 0 point batch test cases act like pretests
Also add a `points` field to `BatchedTestCase`.

Add Short Circuiting for Zero Point Batches

---

dmoj/graders/interactive.py

Allow the user-written `interact` method to return a `CheckerResult` *or* a bool for the `InteractiveGrader` to use.

Allow interactive judge to return a CheckerResult

---

dmoj/judge.py
dmoj/problem.py

Allow for a key, `sc`, within the `init.yml` to dictate on a per-batch basis whether or not said batch should be short circuited. Can be combined with #212 .

Allow batches to not short circuit

---

dmoj/checkers/floats.py
dmoj/checkers/floatsabs.py
dmoj/checkers/floatsrel.py
dmoj/checkers/linecount.py
dmoj/checkers/rstripped.py
dmoj/checkers/sorted.py
dmoj/graders/standard.py
dmoj/problem.py

Normalize `process_output`, which will prevent checkers like `floats`, etc, from failing on Windows due to the presence of `\r\n`.

Normalize `process_output`

---

dmoj/graders/interactive.py

Previously, the interactive grader only checked for WA/AC, which lead to strange verdicts such as TLEs getting full credit.

Prevent interactive TLEs from getting full credit

---

dmoj/executors/java_executor.py
dmoj/executors/mixins.py
dmoj/tests/test_malformed_unicode.py

Modified the regexes in `dmoj.executor.java_executor` to account for Unicode submissions, and added a unit test for malformed UTF-8.

Detect Unicode Classes in Java; #311

---

dmoj/cptbox/sandbox.py

Some systems (like Termux by default) do not ship with `file(1)`, in which case the judge crashes with a poor error message in unrelated code. Addresses #309.

Gracefully handle no `file` executable

---

dmoj/graders/standard.py

DMOJ does not currently support POI-style grading. This commit exposes execution time to enable POI-style grading as checkers are able to assign custom point values.

add execution time to checker

---

dmoj/checkers/identical.py

The only people who understand what Presentation Error is are the people who are the least likely to run into it.
Presentation Error is no longer a standard verdict in the modern competitive programming meta. In the interest of being more user-friendly, the recipient is given a explicit call to action.

make presentation error message more user-friendly

---

.travis.yml
README.md
dmoj/cptbox/_cptbox.pyx
dmoj/cptbox/handlers.py
dmoj/cptbox/helper.cpp
dmoj/cptbox/helper.h
dmoj/cptbox/ptbox.h
dmoj/cptbox/ptdebug.cpp
dmoj/cptbox/ptproc.cpp
dmoj/cptbox/sandbox.py
dmoj/executors/mono_executor.py
dmoj/judge.py
setup.py

This change has been tested to work on x64 for a couple of critical
executors. There might exist some loose ends on ARM.
`seccomp` is used to remove the need to return from `ptrace` for all
syscalls that occur, allowing us to selectively filter more dangerous
syscalls (like `open`), while incurring a smaller penalty for frequent,
but harmless, syscalls (like `write`).
There are a number of semantic differences between pure `ptrace` and
`ptrace` + `seccomp`. Notably, where `ptrace` has pre- and post-syscall
events, `ptrace` + `seccomp` only fires a pre-syscall event.
Nonetheless, functionality like switching syscall registers around works
fine in the pre-syscall event.
A smaller distinction as a result of this is that to cancel a syscall, we
need to pass in -1 as the modified syscall, …

Implement seccomp filtering optimization

---

dmoj/checkers/linecount.py
dmoj/graders/standard.py

Some contests (e.g. ECOO) will check partial output, regardless of if there is a TLE/IR/RTE verdict.

Optionally allow for checkers to always run

---

dmoj/config.py
dmoj/generator.py
dmoj/problem.py

By specifying `compiler_time_limit: 60` on the `generator_multifile` test, Appveyor will actually pass all tests.

Allow generators to specify custom compiler TL; #295

---

dmoj/executors/java_executor.py

In Python 3, having a compile error with Unicode in the output causes:
```
Traceback (most recent call last):
File "/code/judge/dmoj/judge.py", line 276, in get_grader_from_source
grader = grader_class(self, problem, language, utf8bytes(source))
File "/code/judge/dmoj/graders/base.py", line 10, in __init__
self.binary = self._generate_binary()
File "/code/judge/dmoj/graders/standard.py", line 175, in _generate_binary
unbuffered=self.problem.config.unbuffered)
File "/code/judge/dmoj/executors/base_executor.py", line 314, in __call__
obj.compile()
File "/code/judge/dmoj/executors/base_executor.py", line 439, in compile
self.handle_compile_error(output)
File "/code/judge/dmoj/executors/java_executor.py", line 238, in handle_compile_error
if b'is public, should be declared in a file named' in …
```

Fix IE with Unicode in Java compile error output.

---

.travis.test.py

PYTHON_E241: 'Fix extraneous whitespace around keywords.'.  This is a pep8 error code.          See <a href='https://pep8.readthedocs.io/en/latest/intro.html#error-codes'>        here for a complete list of error codes</a>.
It was fixed with <a href='https://github.com/hhatto/autopep8'>autopep8</a>.  The fix is completely safe.

Fixed 4 issues of type: PYTHON_E241 throughout 1 file in repo.

---

dmoj/executors/python_executor.py

PYTHON_W291: 'Remove trailing whitespace.'.  This is a pep8 error code.          See <a href='https://pep8.readthedocs.io/en/latest/intro.html#error-codes'>        here for a complete list of error codes</a>.
It was fixed with <a href='https://github.com/hhatto/autopep8'>autopep8</a>.  The fix is completely safe.

Fixed 1 issue of type: PYTHON_W291 throughout 1 file in repo.

---

dmoj/executors/DART.py
dmoj/executors/FORTH.py
dmoj/executors/MONOVB.py
dmoj/executors/TCL.py
dmoj/executors/TEXT.py

PYTHON_W391: 'blank line at end of file'.  This is a pep8 error code.          See <a href='https://pep8.readthedocs.io/en/latest/intro.html#error-codes'>        here for a complete list of error codes</a>.
It was fixed with <a href='https://github.com/hhatto/autopep8'>autopep8</a>.  The fix is completely safe.

Fixed 5 issues of type: PYTHON_W391 throughout 5 files in repo.

---

dmoj/cli.py

Currently if you give the CLI an empty newline you get:
```
dmoj>
Traceback (most recent call last):
File "/usr/local/bin/dmoj-cli", line 11, in <module>
load_entry_point('dmoj', 'console_scripts', 'dmoj-cli')()
File "/code/judge/dmoj/cli.py", line 85, in main
sys.exit(cli_main())
File "/code/judge/dmoj/cli.py", line 145, in cli_main
run_command(shlex.split(command))
File "/code/judge/dmoj/cli.py", line 122, in run_command
if line[0] in commands:
IndexError: list index out of range
```

Ensure empty newline does not crash CLI

---

dmoj/cptbox/chroot.py
dmoj/graders/standard.py

This breaks IO symlinks; this will be addressed in a future commit.

cptbox: Unconditionally disallow writing to files

---

dmoj/executors/COFFEE.py

The COFFEE self-test fails if you do not enable this syscall.

COFFEE: enable `epoll_pwait` syscall

---

dmoj/executors/PYPY.py
dmoj/executors/base_executor.py
dmoj/executors/gcc_executor.py

`g++` appears to no longer provide minor/bugfix information as of version 8:
```
$ g++ -dumpversion
8
```

Allow single-digit runtime version formatting

---

dmoj/config.py

`0 or None` evaluates to `None`, and with most signature-graded and many custom graded problems setting `output_prefix_length` to `0`, this caused the database to get hammered if a use submitted a program that produced large amounts of output on said problems.

Allow config keys to have a value of `0`

---

dmoj/executors/COFFEE.py

This allows for the CoffeeScript executor to work with CoffeeScript v2.2.0.

Allow `eventfd2` syscall

---

dmoj/executors/GO.py

This allows GO 1.11.6 to work with the judge.

Add `$GOCACHE` to compile env

---

dmoj/executors/CLANG.py
dmoj/executors/CLANGX.py
dmoj/executors/clang_executor.py

`clang -dumpversion` always returns 4.2.1 for compatibility reasons.

Correctly display clang version

---

dmoj/executors/java_executor.py

Inform Java users of missing `main(String[] args)`

---

dmoj/executors/java_executor.py

New message is 49 characters long, so it will not be truncated.

Shorten error message when entry point is not found; #366

---

dmoj/executors/RUBY2.py

The latest stable release of Ruby is 2.6.4, while the current executor only supports up to Ruby 2.4.

Bump up ruby command path to support Ruby 2.6

---

.gitignore

Note: When invoking mypy, a `.mypy_cache` directory is created.

add mypy_cache to gitignore

---

dmoj/executors/RUST.py

This is in preparation for making extensions mandatory
in all executors.

Add missing extension to Rust executor

---

dmoj/executors/java_executor.py

`compiler` and `vm` look mandatory across all existing subclasses, `jvm_regex` looks to be `Optional`.

Fix untyped mypy errors from java_executor.py

---

dmoj/executors/base_executor.py

There is an entire class of executors that doesn't
use the command attribute, which is why it's
Optional and not simply str.

Type command on BaseExecutor as Optional

---

dmoj/utils/unicode.py

mypy considers the original return statements to be
errors since they omit the implicit None.

Add mypy types to utils/unicode.py

---

dmoj/executors/asm_executor.py

The syntax is now much simpler, but the downside is that `ABCMeta` will not forbid construction if they variables are not actually declared. Instead, using the variable causes an exception at runtime. I think in either case the exception happens at runtime, so it's probably fine.

Use Python 3.6+ declarations for asm_executor.py annotations

---

dmoj/executors/clang_executor.py

Limit Clang/++ compile errors; #487

---

dmoj/checkers/floats.py
dmoj/tests/test_checker.py

Use `Decimal` in floats checker

---

dmoj/checkers/floats.py
dmoj/tests/test_checker.py

Reverts DMOJ/judge#503.
This is completely broken. The checker will reject anything because `Decimal` constructor does not accept `bytes`. Once that bug is fixed, the inability to control `Decimal`'s precision makes the `assert not check(b'0.' + b'1' * 100, b'0.' + b'1' * 99, high_precision=True, error_mode='absolute')` test case fail, since the numbers do compare equal at default precision.
In other words, the only test case worked by accident.

Revert "Use `Decimal` in floats checker"

---

dmoj/executors/RUST.py

This will fail if `cargo` isn't in the same directory as `rustc`. I don't think being robust here is worth it.

Report rustc version instead of cargo version; fixes #534

---

README.md
dmoj/executors/JAVA11.py

No automated tests for this currently. If we're lucky and `bionic` works, we'll gain Java 9 coverage at most.

Add Java 11 executor

---

dmoj/generator.py
dmoj/judgeenv.py

Sets the default generator compiler time limit to 30s, so testlib compilation won't timeout during compilation of generators.

Add Generator Compiler Time Limit

---

dmoj/commands/problems.py

Otherwise trying to filter by name yields the error:
```
Traceback (most recent call last):
File "/usr/local/bin/dmoj-cli", line 11, in <module>
load_entry_point('dmoj', 'console_scripts', 'dmoj-cli')()
File "/code/judge/dmoj/cli.py", line 68, in main
sys.exit(cli_main())
File "/code/judge/dmoj/cli.py", line 121, in cli_main
run_command(shlex.split(command))
File "/code/judge/dmoj/cli.py", line 101, in run_command
return cmd.execute(line[1:])
File "/code/judge/dmoj/commands/problems.py", line 33, in execute
if len(all_problems):
TypeError: object of type 'filter' has no len()
```

Ensure `all_problems` is always a list

---

.travis.yml

This unfortunately only works when you know the file name, so it cannot replace the other instances. But this should solve our immediate problems.

Use direct link to latest release

---

dmoj/cptbox/_cptbox.pyx

Fixes #588.
More testing will be done before this is marked ready for review.

Hold GIL when calling pt_process::spawn; fixes #588

---

.docker.test.py
.github/workflows/flake8.yml
.travis.yml
dmoj/checkers/linecount.py
dmoj/executors/V8JS.py

Travis linting is fixed, but I don't know if it is really necessary. Linting on Travis allows builds to fail early, which might be good, but also adds an extra minute to Travis since it can't be parallelized this way.

Restore flake8

---

dmoj/judgeenv.py

Follow-up to 59b98ea, allowing existing checkers to see speedups as
well, and reduce reliance on VM caching setup.

judgeenv: memoize problem root lookups

---

dmoj/checkers/bridged.py
dmoj/generator.py
dmoj/graders/bridged.py
dmoj/problem.py
dmoj/utils/helper_files.py

* Allows for passing of flags to generators and bridged checkers
* Allows for generators and bridged checkers to be not cached
* Fixes regression with bridged checker introduced in 0c08757
* Convert `dmoj.utils.aux_files` to Unix line endings

Fix `compile_with_auxiliary_files`

---

dmoj/executors/ZIG.py

This is equivalent to -O2 in C compilers

Turn on --release-safe mode for Zig

---

dmoj/executors/ZIG.py

Zig will not compile because ace wants `\r\n`! 
https://github.com/ziglang/zig/issues/544
me: psh I don't need to end to end test what could possibly go wrong
zig: haha strictness machine go brrrr

make the \r in zig go bye bye

---

dmoj/problem.py

Default points to 1, since we do this for test automatching anyway.
Fixes #659.

Fix TypeError in site when judge sends None case points

---

dmoj/cli.py
dmoj/cptbox/_cptbox.pyx
dmoj/cptbox/isolate.py
dmoj/cptbox/ptbox.h
dmoj/cptbox/ptdebug.cpp
dmoj/cptbox/tracer.py

Otherwise, we can end up failing ptrace PEEKDATA, and return a garbage
path that only fails the sandbox check by accident.

cptbox: validate null file paths

---

dmoj/judgeenv.py

This should prevent issues with flaky NFS / syncing when moving problem
directories, which has sometimes left hanging problem directories in
connected judges (but no init.yml files).
This then leads to errors like
```
dmoj.config.InvalidInitException: 'file "init.yml" could not be found in "/problems/site/dmopc19c7p1"'
```
...that shouldn't happen, since there is a problem directory with that code that _does_ contain an `init.yml`, elsewhere.
Ideally hanging directories shouldn't happen in the first place, but accepting a universe where they do, not failing on our end is the next best thing.

judgeenv: only treat directories with init.yml as problems

---

dmoj/judge.py
dmoj/packet.py

We already handle the case where we fail on recv, which is more likely.
Fixes #685.

packet: cleanly exit judge on write failure

---

dmoj/executors/AWK.py
dmoj/executors/BASH.py
dmoj/executors/COFFEE.py
dmoj/executors/DART.py
dmoj/executors/FORTH.py
dmoj/executors/GROOVY.py
dmoj/executors/KOTLIN.py
dmoj/executors/PERL.py
dmoj/executors/PHP.py
dmoj/executors/PRO.py
dmoj/executors/RKT.py
dmoj/executors/RUBY2.py
dmoj/executors/SBCL.py
dmoj/executors/SCALA.py
dmoj/executors/SED.py
dmoj/executors/TUR.py
dmoj/executors/V8JS.py
dmoj/executors/asm_executor.py
dmoj/executors/base_executor.py
dmoj/executors/compiled_executor.py
dmoj/executors/java_executor.py
dmoj/executors/mixins.py
dmoj/executors/mono_executor.py
dmoj/executors/python_executor.py
dmoj/executors/script_executor.py

This removes the need for ugly hacks like caching the current
invocation's values in `launch`.

Provide launch kwargs to executor `get_cmdline`

---

dmoj/commands/resubmit.py
dmoj/commands/submit.py

This is more of a QOL improvement. Currently, when there is a long running submission (e.g a submission that TLEs on every case), there is no way to abort the submission. Pressing `Ctrl-C` would kill the CLI, potentially losing any commands that were previously typed and had scrolled off the screen (since there is no persistent history). Thus, the only way would be to wait out the grading.
In this PR, instead of killing the CLI directly while a submission is grading, we first kill the currently grading submission if there is one.

Kill the judging submission first with a keyboard interrupt on CLI

---

dmoj/judge.py

Otherwise, the controller can run out of RAM buffering testcase updates.

ipc: trim submission output before sending to controller

---

dmoj/contrib/testlib.py

`stderr` is not guaranteed to be empty when parsing partials.

Improvements to partial point parsing

---

.docker/entry

This reverts commit b43e4a275d93f0f2bfda76229c10ba73458ff697.
The underlying issue that kept blowing up memory fragmentation even
post-IPC-judge-rewrite was fixed in e1a9b23, and glibc malloc has a
slightly smaller baseline memory footprint.

Revert "Revert "Stop using jemalloc in Docker""

---

dmoj/contrib/coci.py

ContribModule for COCI style problems, which often specify a fraction of points earned for a subtask. For example: https://dmoj.ca/problem/coci19c6p4.
This uses testlib return codes, and supports fractions in the range [0, 1]. Similar to the [testlib ContribModule](https://github.com/DMOJ/judge-server/blob/master/dmoj/contrib/testlib.py), the fraction is outputted to stderr in the form `partial n/d`, where `n` is a non negative integer specifying the numerator, and `d` is a positive integer specifying the denominator. This fraction represents the fraction of points earned for that subtask.  For example, if the subtask is worth 10 points, and the output to stderr is `partial 1/3` (with return code 7), then 3.3333... points are earned for that subtask.

Added COCI ContribModule for fraction of points in bridged checker

---

dmoj/cptbox/helper.cpp

This trades performance for security, as the original code went through
libseccomp syscall translation and did not allow the correct syscalls.

cptbox: construct empty filter when executing x86-on-x64

---

dmoj/cptbox/isolate.py
dmoj/executors/mixins.py
dmoj/testsuite.py

Since we now EPERM rather than kill, we no longer need these rules.

De-whitelist resolv.conf and nsswitch.conf

---

dmoj/problem.py

This will allow graders to inherit from e.g
`BridgedInteractiveGrader` without doing sketchy things with
the problem config. Currently, `BridgedInteractiveGrader` is used
if the `interactive` key is in the problem dictionary, while
it is also accessed in that grader's constructor. This gives
no easy way to inherit from this grader without touching the
problem config or Python's internals.

Check `custom_judge` first before other graders

---

dmoj/graders/signature.py

Some problems (e.g. CEOI '18 P6) use signature grading to emulate interaction, and so require the main to be left intact.
Fixes #730.

Add flag to allow siggrader to not overwrite main function; fixes #730

---

dmoj/checkers/bridged.py
dmoj/contrib/peg.py
dmoj/graders/bridged.py

According to @t3nsor, the correct order is `<checker> <judge answer> <program output> <input> <source file>`. (I suspect we can get away with not passing the source file in 99% of cases)
Additionally, printing a ratio of floats is valid.
NOI '04 P1 (which I based this code off of) just happened to have poor choice in variable names...

contrib: Correct inaccuracies in PEG contrib module 

---

dmoj/graders/standard.py

To begin with, we don't support PyPy at all.

graders/standard: remove misleading PyPy branch

---

.travis.yml
dmoj/tests/test_control.py
dmoj/utils/module.py

This PR also fixes instances of deprecation and other warnings. This should prepare DMOJ for the release of Python 3.10, which will be removing old deprecated Python 2 names.

Test for absence of deprecation and other warnings on CI

---

dmoj/executors/java_executor.py

It has not been used by anything in years.

Remove last occurrence of `launch_unsafe`

---

dmoj/judgeenv.py

Problem globs is on hold due to time constraints, and this fix should occur regardless (as we decided v2 of judge should still support `problem_storage_root`).

Fix `problem_watches` watching nonsense directories; #723

---

dmoj/judge.py

Letting this be an option is an invitation for people to use it without understanding the (major) repercussions, so let's just remove it.

judge: disallow running as root

---

dmoj/executors/GO.py

See example below:
```
root@4b0a20c790c2:/tmp/foo# CGO_ENABLED=0 GOCACHE=$(pwd) go build a1.go 
go build command-line-arguments: build output "a1" already exists and is a directory
root@4b0a20c790c2:/tmp/foo# ls
00  06	0c  12	18  1e	24  2a	30  36	3c  42	48  4e	54  5a	60  66	6c  72	78  7e	84  8a	90  96	9c	a1     a6  ac  b2  b8  be  c4  ca  d0  d6  dc  e2  e8  ee  f4  fa  trim.txt
01  07	0d  13	19  1f	25  2b	31  37	3d  43	49  4f	55  5b	61  67	6d  73	79  7f	85  8b	91  97	9d	a1.go  a7  ad  b3  b9  bf  c5  cb  d1  d7  dd  e3  e9  ef  f5  fb
02  08	0e  14	1a  20	26  2c	32  38	3e  44	4a  50	56  5c	62  68	6e  74	7a  80	86  8c	92  98	9e	a2     a8  ae  b4  ba  c0  c6  cc  d2  d8  de  e4  ea  f0  f6  fc
03  09	0f  15	1b  21	27  2d	33  39	3f  45	4b  51	57  5d	63  69	6f  75	7b  81	87  8d	93  99	9f	a3 …
```

GO: use subdirectory for cache; fixes #770

---

dmoj/executors/DART.py
dmoj/executors/FORTH.py
dmoj/executors/RKT.py
dmoj/executors/SBCL.py
dmoj/executors/mixins.py
dmoj/executors/python_executor.py

Its functionality was absorbed by the standard executor base for a while
now.

executors: remove ScriptDirectoryMixin

---

dmoj/executors/gcc_executor.py
dmoj/executors/java_executor.py
dmoj/executors/mixins.py

```
root@53a4f2640160:/usr/lib/jvm# java-15-openjdk-amd64/bin/javac -version
javac 15
root@53a4f2640160:/usr/lib/jvm# java-1.8.0-openjdk-amd64/bin/javac -version
javac 1.8.0_265
```

executors: allow single-digit runtime version formatting for Java

---

dmoj/executors/GROOVY.py

We were not passing up `**kwargs` to `JavaExecutor`.

GROOVY: fix initialization exception

---

dmoj/cptbox/isolate.py
dmoj/executors/COFFEE.py
dmoj/executors/HASK.py
dmoj/executors/RKT.py
dmoj/executors/RUBY2.py
dmoj/executors/SBCL.py

There is little point restricting `sys_poll` when we allow `sys_select`.

Allow sys_poll globally to fix RUST failure

---

setup.py

Platform | Single time | Parallel time | Speed up | Saved
-- | -- | -- | -- | --
Ryzen 9 3900X | 3.743 | 2.557 | 1.463824795 | 1.186
Raspberry Pi 3 (armhf) | 73.19 | 42.921 | 1.70522588 | 30.269
Raspberry Pi 3 (arm64) | 83.418 | 47.355 | 1.761545771 | 36.063
While this offers a negligible improvement on fast machines (saves around 1 second), it can mean a lot on slower multicore machines, such as the Raspberry Pi 3. The improvements would be more impressive if only `_cptbox` was the only extension being built.

Build C extensions in parallel

---

dmoj/cptbox/_cptbox.pyx
dmoj/cptbox/ptbox.h
dmoj/cptbox/ptdebug_arm.cpp
dmoj/cptbox/ptdebug_arm64.cpp
dmoj/cptbox/ptdebug_freebsd_x64.cpp
dmoj/cptbox/ptdebug_x64.cpp
dmoj/cptbox/ptdebug_x86.cpp
dmoj/cptbox/ptproc.cpp
dmoj/cptbox/tracer.py
dmoj/result.py
dmoj/utils/error.py
dmoj/utils/helper_files.py

Closes #797
* `pre_syscall` errno is now tracked and failure now results in a protection fault, e.g.
```
WARNING 2020-12-29 00:17:50,494 error Protection fault on: -1 (ptrace fail)
WARNING 2020-12-29 00:17:50,495 error Arg0: 0x0000000000000000
WARNING 2020-12-29 00:17:50,495 error Arg1: 0x0000000000000000
WARNING 2020-12-29 00:17:50,495 error Arg2: 0x0000000000000000
WARNING 2020-12-29 00:17:50,495 error Arg3: 0x0000000000000000
WARNING 2020-12-29 00:17:50,495 error Arg4: 0x0000000000000000
WARNING 2020-12-29 00:17:50,495 error Arg5: 0x0000000000000000
```
* `post_syscall` failures are now converted into a special protection fault, e.g.
```
WARNING 2020-12-28 00:56:47,105 error Failed to alter system call: 41 (sys_socket) with error 1 (EPERM): Operation not permitted
WARNING 2020-12-28 …
```

Handle pre-/post-syscall errors

---

dmoj/cptbox/ptbox.h
dmoj/cptbox/ptdebug_arm.cpp
dmoj/cptbox/ptdebug_arm64.cpp
dmoj/cptbox/ptdebug_freebsd_x64.cpp
dmoj/cptbox/ptdebug_x64.cpp
dmoj/cptbox/ptdebug_x86.cpp
dmoj/cptbox/ptproc.cpp
dmoj/cptbox/tracer.py

Correctly ensure that process initialization is correctly detected (i.e. `pt_proc::_initialized` is correctly set). Also add an exception to be thrown if the process exited successfully without setting the initialization flag, allowing such bugs in the future to be detected.

Fix logic related to process initialization detection

---

dmoj/executors/java_executor.py

This allows custom executors (e.g. for CTFs) to not hardcode
the precise argument list for the rest of the VM.
/cc @ehhthing

java: move agent flag generation to a helper

---

dmoj/cptbox/ptbox.h
dmoj/cptbox/ptproc.cpp

Basically implement `pt_debugger::is_syscall()` on FreeBSD.

Fix cptbox build issues on FreeBSD

---

dmoj/cptbox/_cptbox.pyi
dmoj/cptbox/_cptbox.pyx
dmoj/cptbox/helper.cpp
dmoj/cptbox/helper.h
dmoj/cptbox/utils.py
dmoj/tests/test_memory_io.py

This class can be used to create virtual files backed by memory and
later pass them as input to other processes, e.g. user submissions.
These virtual files can be sealed to prevent modification after
passing them to other processes.
On FreeBSD, we use shm_open(SHM_ANON) as a fallback option, which
should do similar things. Note that sealing is not supported on
FreeBSD.
Unit tests were also added.

Implement memfd-backed MemoryIO class

---

dmoj/tests/test_int_patch.py
dmoj/utils/builtin_int_patch.py

The current behaviour requires an argument to be passed to `int(...)`, however, this breaks `defaultdict(int)`.

Allow for checkers to call `int()`

---

.github/workflows/update-syscalls.yml

The current behaviour is using whoever committed last on master as the author.
This is clearly a misattribution.

Set update-syscalls PR author to dmoj-build

---

setup.py

We released 3.0.x after adding 3.9 support and forgot to tag it properly.

Add python 3.9 classifier to setup.py

---

.docker/tier1/Dockerfile
.docker/tier2/Dockerfile
.docker/tier3/Dockerfile

This fixes $HOME pointing to /root, fixing the following error during
autoconf:
/bin/sh: 31: .: cannot open /root/.cargo/env: No such file
An alternative here would be to use the USER Docker directive, but that
required making /judge-runtime-paths.yml writable by the judge user.
This is simpler.

docker: set $HOME before sourcing profile

---

dmoj/cptbox/isolate.py
dmoj/executors/mixins.py

We won't be able to support this with Landlock.

cptbox: disallow rules that require current {pid} formatting

---

dmoj/cptbox/ptproc.cpp
setup.py

It appears that WSL 1 uses capitalized "Microsoft" while WSL2 doesn't,
and this is used to distinguish between the WSL versions.

Detect WSL 1 and apply waitpid hack to it only

---

dmoj/cptbox/_cptbox.pyx
dmoj/cptbox/handlers.py
dmoj/cptbox/ptbox.h
dmoj/cptbox/ptdebug.cpp
dmoj/cptbox/ptdebug_freebsd_x64.cpp

This allows errno to be set correctly on FreeBSD.

cptbox: use generic errno setter

---

.github/workflows/build.yml

We no longer have Debian buster tethering us to the old Python 3.7, so let's upgrade.

ci: use python 3.9 for lint/mypy/sdist jobs

---

testsuite/helloworld/tests/py3_bad_file/helloworld.py
testsuite/helloworld/tests/py3_bad_file/test.yml

`/dev/full` is is a device file that exists and can be opened by all users, but not actually useful and never actually used:
```console
$ ls -l /dev/full 
crw-rw-rw- 1 root root 1, 7 Aug 22 05:43 /dev/full
```

testsuite: add test to make sure ENOENT is generated

---

.github/workflows/build.yml
dmoj/cptbox/isolate.py
dmoj/cptbox/tracer.py
dmoj/executors/asm_executor.py
dmoj/judge.py
dmoj/judgeenv.py
requirements.txt

This adds the package `flake8-import-order` (https://github.com/PyCQA/flake8-import-order), in order to check for import ordering in flake8. It also fixes any current ordering errors.

add flake8-import-order

---

dmoj/cptbox/tracer.py
dmoj/utils/os_ext.py

There is no way `find_exe_in_path` actually works on Python 3 due to `str`/`bytes` confusion.

cptbox: remove bit-rotten find_exe_in_path

---

.freebsd.test.py
dmoj/cptbox/filesystem_policies.py
dmoj/cptbox/isolate.py
dmoj/executors/COFFEE.py
dmoj/executors/DART.py
dmoj/executors/FORTH.py
dmoj/executors/PERL.py
dmoj/executors/PHP.py
dmoj/executors/RKT.py
dmoj/executors/RUBY2.py
dmoj/executors/SWIFT.py
dmoj/executors/TUR.py
dmoj/executors/java_executor.py
dmoj/executors/mixins.py
dmoj/executors/mono_executor.py
dmoj/executors/script_executor.py
dmoj/judgeenv.py
dmoj/tests/test_filesystem_policy.py
dmoj/utils/helper_files.py

This is the first step of migrating to Landlock support. A very simplistic implementation is given here.

change regex to filesystem policy matcher, first step of #871

---

dmoj/cptbox/_cptbox.pyx
dmoj/cptbox/handlers.py
dmoj/cptbox/handlers.pyi
dmoj/cptbox/helper.cpp
dmoj/cptbox/helper.h
dmoj/cptbox/isolate.py
dmoj/cptbox/tracer.py
testsuite/helloworld/tests/sandbox_py3_mkdir/helloworld.py
testsuite/helloworld/tests/sandbox_py3_mkdir/test.yml

cptbox: implement seccomp errno generation

---

dmoj/cptbox/ptproc.cpp
dmoj/cptbox/tracer.py

We used to invoke the handler immediately after the syscall, but that's imperfect. Instead, we use the Linux 4.8+ behaviour that allows us to receive a syscall-exit-stop right after `PTRACE_EVENT_SECCOMP`, allowing us to implement `on_return` for real.
Naturally, this disables seccomp on kernels before 4.8.

cptbox: make return callbacks work with seccomp

---

dmoj/executors/mixins.py

These files are not POSIX, so runtimes should not be relying on their
presence.

executors: disallow /dev/std{in,err,out}

---

dmoj/cptbox/isolate.py

Landlock returns this, not EPERM.

Change EPERM into EACCES for file access

---

dmoj/executors/java_executor.py

previously, an erroneous directory was chosen for the JVM config. To 
ensure a good path is chosen, we use a glob, and resolve the VM path.

fix java executors VM config detection

---

dmoj/cptbox/ptproc.cpp

PTRACE_O_EXITKILL was introduced in Linux kernel 3.8, and our minimum
requirement is 4.8.

cptbox: remove #ifdef for PTRACE_O_EXITKILL

---

dmoj/executors/compiled_executor.py

This handles the case where times is NULL, which is valid and should not
generate EFAULT.

cptbox: make sys_utimensat emulation more accurate

---

dmoj/cptbox/ptproc.cpp

This deals with flakiness when a child process gets killed on Linux, which
manifests as randomly failing Go compiles. Since Go is not INTERCAL, we
strive to avoid such "random compiler bugs".

cptbox: ignore ESRCH from post_syscall handler

---

dmoj/cptbox/helper.cpp

The fcntl(F_CLOSEM) approach is only needed for FreeBSD releases out of
support for over 6 years, and the code path doesn't even work as it used
the wrong variable name.

cptbox: drop support for FreeBSD < 8

---

dmoj/cptbox/tracer.py
dmoj/executors/compiled_executor.py

This avoids the hack of using a callback that returns True.

cptbox: correctly handle sys_execve being allowed with seccomp

---

dmoj/executors/mixins.py

On some platforms, e.g. arm64, gcc tries to look for non-existent
directories under /usr, and complains when forbidden to do so. To fix this,
we must allow the entirety of /usr.
The only reason we don't allow the entirety of /usr is because on FreeBSD,
home directories are located in /usr/home. However, this is easily fixed
by using the current logic if /usr/home exists, and otherwise allow
everything under /usr.

executors: improve /usr handling

---

dmoj/config.py

Currently, it is impossible to store `null` in the YAML config file to
override a non-null default value, as it will always fallback due to
the or.
This manifests as broken `-march=native` removal for gcc/clang.

config: fix ConfigNode.get fallback logic

---

testsuite/helloworld/tests/monocs_mle/test.posix.yml

This should hopefully avoid flakiness with memory usage on FreeBSD.

testsuite: reduce memory limit for C# MLE test

---

.docker.test.py

Groovy is expected to be permanently fixed with the removal of Java security managers, and GASARM works now on arm64.

ci: allow less executors to fail

---

dmoj/executors/base_executor.py
dmoj/executors/shell_executor.py

See [PEP 632](https://www.python.org/dev/peps/pep-0632/#migration-advice), which suggests replacing `distutils.spawn.find_executable` with `shutil.which`.

executors: use shutil.which instead of deprecated distutils

---

dmoj/citest.py

Most notably, this removes a dependency on `distutils.version.LooseVersion`, which is deprecated in [PEP 632](https://www.python.org/dev/peps/pep-0632/).

ci: remove useless functions from citest.py

---

.clang-format
.github/workflows/build.yml
dmoj/cptbox/ext_freebsd.h
dmoj/cptbox/helper.cpp
dmoj/cptbox/helper.h
dmoj/cptbox/ptbox.h
dmoj/cptbox/ptdebug.cpp
dmoj/cptbox/ptdebug_arm.cpp
dmoj/cptbox/ptdebug_arm64.cpp
dmoj/cptbox/ptdebug_freebsd_x64.cpp
dmoj/cptbox/ptdebug_x64.cpp
dmoj/cptbox/ptdebug_x86.cpp
dmoj/cptbox/ptproc.cpp

Broken example: https://github.com/DMOJ/judge-server/runs/3671774719?check_suite_focus=true

cptbox: clang-format

---

dmoj/executors/PAS.py

This was inherited from PEG, but doesn't seem to be specified by other
online judges.
-So
Try to be Borland TP 7.0 compatible (no function overloading etc.).

executors/PAS: drop -So argument

---

dmoj/cptbox/isolate.py

This will fix the current runtimes-docker CI breakage.

cptbox: check faccessat2 instead of always denying

---

dmoj/cptbox/isolate.py
dmoj/executors/compiled_executor.py

It used to only be allowed for compilers, but there is no reason why
it should be compiler-only given that other stat syscalls are allowed
for everything.
This will fix the failure with Turing on latest glibc.

cptbox: allow statx by default

---

.docker/tier1/Dockerfile
.docker/tier2/Dockerfile
.docker/tier3/Dockerfile

Fixes #974. I borrowed code from [this commit](https://github.com/DMOJ/runtimes-docker/commit/ad6a42d9f766392987ff9702d7614dc4a86c5a71).

Work around pip bug

---

.docker.test.py
README.md
dmoj/cptbox/isolate.py
dmoj/executors/LEAN4.py

Coq can't do I/O. Agda requires a resource-intensive command `cabal install Agda`. Lean 3 can't generate an executable (but it can compile `.lean` to `.olean` for a performance boost). The next best language is Lean 4.
How to test this:
- Install Lean 4 to `/opt/lean`
```bash
mkdir /opt/lean
curl --compressed -L "https://github.com/leanprover/lean4/releases/download/v4.0.0-m2/lean-4.0.0-m2-linux.tar.gz" | tar xz -C /opt/lean --strip-components=1
export PATH="/opt/lean/bin:$PATH"
```
- Modify `.docker.test.py` and `dmoj/citest.py` to just test `LEAN4`
- ![Capture](https://user-images.githubusercontent.com/14223529/148033474-720f5397-e20c-492b-86c1-fffca498ec4e.PNG)
(nit: the version is actually `4.0.0-m2`)
(Lean 4 has some support for siggrading, so it's possible to host a theorem proving …

Add executor for Lean 4

---

.docker.test.py

- Remove `JAVA9` and `JAVA10`, because they're not added to `failed_executors`.
- `LEAN4` should only fail for aarch64.

Update docker test

---

.github/workflows/update-syscalls.yml
dmoj/cptbox/syscalls/generate.py

Basically don't say Linux in the PR title or commit message since we generate FreeBSD too now.

ci: improve automatic syscall PR generation

---

dmoj/packet.py

Currently, `_send_packet` doesn't check if all data has been sent. This is problematic when the number of problems is large, so the packet can't be sent in one pass. This PR fixes that.

Use socket.sendall to send packets

---

dmoj/cli.py
dmoj/judge.py
dmoj/judgeenv.py
dmoj/testsuite.py

This avoids spam but allows it when explicitly asked for.

Implement debug mode with debug logging level

---

dmoj/cptbox/__init__.py
dmoj/cptbox/isolate.py
dmoj/executors/compiled_executor.py

It was confusing that it was handling both `open`/`fstat` in non-obvious
ways.

cptbox: make `_file_access_check` syscall-agnostic

---

.flake8
dmoj/cptbox/compiler_isolate.py
dmoj/cptbox/isolate.py
dmoj/executors/compiled_executor.py
dmoj/executors/shell_executor.py

This PR refactors isolate.py, including moving the recently introduced FilesystemSyscallKind into its own file, moving the compiler isolate tracer into cptbox, and splitting up the logic overall.
The main hope is that this PR will make coding on top of this system easier, especially in conjunction with the landlock PR, for implementation of a debug mode.

Isolate refactor

---

.freebsd.test.py
dmoj/executors/RUBY.py

Ruby 2 -> 3 is not a breaking change, so rename the executor to just
`RUBY` and add `ruby3.0` to the search path.

executors: add support for Ruby 3

---

dmoj/cptbox/compiler_isolate.py
dmoj/cptbox/isolate.py
dmoj/executors/base_executor.py
dmoj/executors/compiled_executor.py

Remove legacy `writable` parameter, and make both `read_fs` and `write_fs` required kwargs. Also make `tmpdir` a required kwarg on CompilerIsolateTracer.

cptbox + executors: cleanup IsolateTracer signature

---

dmoj/cptbox/isolate.py

.lstrip() takes a set of characters to strip, so `sys_stat` becomes `tat` under the old system. Observed in logs.

fix syscall name in log

---

dmoj/cptbox/handlers.py
dmoj/cptbox/handlers.pyi
dmoj/cptbox/ptbox.h
dmoj/cptbox/ptproc.cpp

This is from a time when we trapped `write`, and checked the arguments of it, neither of which is true now.

cptbox: remove legacy PTBOX_HANDLER_STDOUTERR

---

dmoj/executors/OBJC.py
dmoj/executors/RUBY.py
dmoj/executors/shell_executor.py

Remove legacy code that added regex strings to the allowed filesystem. Disclaimer: we can't support the regex that OBJC had before, but we can make a best attempt.

executors: remove all regex path checks

---

testsuite/helloworld/tests/sandbox_c_format_open/format_open.c
testsuite/helloworld/tests/sandbox_c_format_open/test.yml

Raised as a concern in #998. We should add an explicit test for this. Note that on seccomp, this returns EACCES, but on landlock, it will return ENOENT, and conceptually, both are reasonable.

testsuite: add test for opening format string

---

dmoj/cptbox/filesystem_policies.py
dmoj/cptbox/isolate.py

There were some missing types in the isolate tracer. Since we need only iterate through the list in the Policy constructor, it need not be a list.

cptbox: add typing and fix typing on rule list

---

dmoj/executors/FORTH.py

This path doesn't exist in Docker, so there's no sense in allowing it.

executors: remove .gforth-history

---

dmoj/cptbox/filesystem_policies.py
dmoj/executors/SWIFT.py
dmoj/executors/ZIG.py
dmoj/executors/compiled_executor.py
dmoj/tests/test_filesystem_policy.py

This is mostly for compatibility with landlock, which enforces this. Builds on top of #999.

cptbox: don't allow paths that don't exist

---

dmoj/executors/base_executor.py
dmoj/packet.py
dmoj/result.py

The first commit simplifies the interface of `get_runtime_versions` so that no mypy asserts are needed.

Report context switches and runtime version to bridge

---

dmoj/cptbox/helper.cpp

I'm assuming this just wasn't cleaned up at some point. Not a lot of point in having a `goto`, in my opinion it just makes this more confusing.

remove goto for failing seccomp

---

dmoj/judge.py
dmoj/problem.py
testsuite/batch_requirements/init.yml

We should do this before anything builds on this. I think `dependencies` is a better name, is more succint, and well-known to programmers.

judge: rename requirements to dependencies

---

.github/workflows/build.yml
dmoj/sysinfo.py
dmoj/tests/test_int_patch.py
dmoj/utils/os_ext.py

This is required to fix compatability with Click 8.1.0. Let's upgrade instead of pinning Click.
See https://github.com/psf/black/pull/2966 and note that all lint jobs fail (see #1021).

Upgrade black to 22.3

---

testsuite/aplusb/tests/java_ac/test.yml

Slower languages like Java tend to flake in FreeBSD CI.

testsuite: increase TL on java aplusb ac

---

dmoj/cptbox/isolate.py

Prevents protection fault for `sys_rseq` on Linux kernel versions >=5.16.

Allow rseq syscall

---

dmoj/cptbox/isolate.py

Java 17 started using it, and we already globally allow `clone`.

isolate: globally allow `clone3`

---

dmoj/utils/builtin_int_patch.py

> when you remember we don't run the latest Python in prod

Make `INT_MAX_NUMBER_DIGITS` backwards compatible

---

dmoj/cptbox/helper.cpp

This avoids non-fatal seccomp errors polluting stderr in generators.

Print seccomp errors to parent stderr

---

.github/workflows/build.yml

This is because our python builds expect the headers in `/code`.
Instead of mounting the tree in /code and copying it to `/judge` where it is executed, we now mount it in `/source` and copy it to `/code` and execute it there.

Use /code paths for python in arm64 CI

---

dmoj/cptbox/isolate.py

Zig is using this to abort itself.

isolate: allow sanitized `tkill`

---

dmoj/executors/KOTLIN.py

executors/KOTLIN: increase compiler time limit

---

dmoj/executors/RUST.py

`cargo build --offline` will happily generate a lock file from the packages we pulled during docker initialization time, so there's no reason to maintain this massive block of text.

executors/RUST: Simplify TOML + Lock

---

dmoj/executors/RUST.py

This will definitely fail in CI. The reason is that [this file](https://github.com/DMOJ/runtimes-docker/blob/master/tier2/Dockerfile#L26-L29) is responsible for the fetching of RUST packages. Since it always fetches from master, only when this PR is merged can CI pass.
To make sure it will pass, I tested locally with:
```
cp ~/Projects/dmoj/judge/judge-server/dmoj/executors/RUST.py . && sed '/^CARGO_TOML/,/^"""/!d;//d' RUST.py > Cargo.toml && sed '/^CARGO_LOCK/,/^"""/!d;//d' RUST.py > Cargo.lock && mkdir -p src && sed '/^HELLO_WORLD_PROGRAM/,/^"""/!d;//d' RUST.py > src/main.rs && cargo fetch
```
Essentially, I do the same thing as the Dockerfile does, fetch the new packages, and then run cargo offline, like it is in Docker:
```
DMOJ_CARGO_OFFLINE=y python3 .docker.test.py
```
This worked …

executors/RUST: update package versions

---

dmoj/executors/RUST.py

Using Rust edition 2021 allows us to avoid `extern crate`, which is old syntax (2015).
Also, the new program actually echos input.
This PR _should_ pass in CI, demonstrating that the new version works, but _should not_ be merged until a corresponding docker PR is ready. In particular, this PR and the docker PR should be merged at the same time.

Rust Edition & Test Program Upgrade

---

.github/workflows/build.yml
.github/workflows/update-syscalls.yml
.github/workflows/upload-pypi.yml

Resolving:
> Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: actions/checkout, actions/setup-python, peter-evans/create-pull-request, actions/checkout

ci: update actions

---

dmoj/graders/base.py
dmoj/judge.py
testsuite/aplusb/init.yml

grader: always run `pretest_test_cases` if available

---

dmoj/cptbox/__init__.py
dmoj/executors/GASARM.py
dmoj/executors/LLC.py
dmoj/executors/asm_executor.py

This appears to work, but we need to get this merged before the runtimes will successfully build, which will enable the tests to pass.

Make LLC executor work on non-amd64 platforms

---

dmoj/judgeenv.py
dmoj/tests/test_globs.py

Also added a test.
Additional question: should we return a problem multiple times if it has different locations?

Fix bug where `get_supported_problems_and_mtimes` won't recursively scan

---

dmoj/executors/base_executor.py
dmoj/judge.py
dmoj/result.py
testsuite/seed2/tests/java_ir/seed2.java
testsuite/seed2/tests/java_ir/test.yml
testsuite/seed2/tests/java_mle/seed2.java
testsuite/seed2/tests/java_mle/test.yml

Fixes a bug where interactive problems will crash upon grading a Java submission that returns `IR` due to `result.proc_output` being the empty string `''` by default. `result.proc_output` should now always be a bytestring.

Declare types for `Result` and `CheckerResult`

---

dmoj/executors/java_executor.py
testsuite/bridged_interactor/tests/java8_grace/seed2.java
testsuite/bridged_interactor/tests/java8_grace/test.yml
testsuite/helloworld/tests/java8_grace/grace.java
testsuite/helloworld/tests/java8_grace/test.yml
testsuite/seed2/tests/java8_grace/seed2.java
testsuite/seed2/tests/java8_grace/test.yml
testsuite/seed2/tests/java_grace/seed2.java
testsuite/seed2/tests/java_grace/test.yml

Changes:
1. print error to `stderr` instead of `stdout`, so we can detect this error within interactive graders
2. add more test cases, because JAVA8 has a slightly different error message, and there is a unique message at 2MB because god is dead and Java killed them

Detect JVM initialization errors

---

dmoj/executors/C.py
dmoj/executors/C11.py
dmoj/executors/CLANGX.py
dmoj/executors/CPP03.py
dmoj/executors/CPP11.py
dmoj/executors/CPP14.py
dmoj/executors/CPP17.py
dmoj/executors/CPP20.py
dmoj/executors/PY2.py
dmoj/executors/PY3.py
dmoj/executors/PYPY.py
dmoj/executors/PYPY3.py

executors: add version checks to self-tests

---

.docker/entry

This makes `docker stop` graceful, since otherwise, `bash` receives SIGTERM, and ignores it. With this setup, `runuser` receives SIGTERM.

Exec final command of docker entry file

---

dmoj/judgeenv.py

The following environment variables may be used to define judge credentials, which are override by the command line arguments:
* `DMOJ_JUDGE_NAME`: for the judge name
* `DMOJ_JUDGE_KEY`: for the judge secret key

Support passing judge credentials through environment

---

dmoj/monitor.py

This is to address watchdog's latest changes of adding `opened` and `closed` event_type.
https://github.com/DMOJ/judge-server/issues/1129#issuecomment-1501174321

Add strict set of events to monitor

---

dmoj/cptbox/_cptbox.pyx

On Cython 3.x, function signatures are by default `noexcept` and functions not declared `noexcept` can't be assigned to them. This
commit marks functions as `noexcept` so that they compile.
Also document `pt_syscall_handler` exception behaviour.
Fixes #1134.

 Make _cptbox.pyx compile on Cython 3.x 

---

.docker/entry

This prevents `runuser` from displaying the judge credentials to everyone on the same machine.

Use setpriv instead of runuser to avoid extra process

---

dmoj/commands/__init__.py
dmoj/commands/locate.py
dmoj/commands/resubmit.py
dmoj/judgeenv.py
dmoj/packet.py
dmoj/tests/test_globs.py

* Add `locate` command: output is
```
Skipped self-tests
Running local judge...
/tmp/problems/a
/tmp/problems/b
c is not a valid problem, skipping
```
for file structure
```
/tmp/problems » tree
.
├── a
│   └── init.yml
└── b
└── init.yml
3 directories, 2 files
```
* Add typing annotations to `dmoj/judgeenv.py`
* Make `get_problem_root` return `None` if the problem does not exist
* Fix typo exposed in `dmoj/commands/resubmit.py` exposed by typing `dmoj/judgeenv.py`
* Fix typing annotation in `dmoj/packet.py`: `os.path.getmtime()` returns a `float` not `int`.

Add `locate` command

---

dmoj/judge.py

- Increase the timeout to 60s to avoid killing the worker when a user has aborted a long-running compilation.
- Rather than display `EOFError` when we kill the worker, display a more informative `TimeoutError` instead.

judge: be more graceful around worker timeouts

---

testsuite/rust_bridged/tests/empty/test.yml
testsuite/rust_generator/README.md
testsuite/rust_generator/generator.rs
testsuite/rust_generator/init.yml
testsuite/rust_generator/tests/AC/sol.py
testsuite/rust_generator/tests/AC/test.yml

This would have caught a failure on #1148.

testsuite: add rust generator test

---

dmoj/commands/__init__.py
dmoj/commands/validate.py
dmoj/contrib/__init__.py
dmoj/contrib/base.py
dmoj/contrib/coci.py
dmoj/contrib/default.py
dmoj/contrib/peg.py
dmoj/contrib/testlib.py
dmoj/error.py
dmoj/graders/base.py
dmoj/judge.py
dmoj/judgeenv.py
dmoj/problem.py
dmoj/utils/helper_files.py

Add to `init.yml`
```yaml
validator:
source: validate.cpp
language: CPP14
time: 2
memory: 65536
```

Add input validation command

---

.docker.test.py

Reverts e2b6533bda8e4a2316de21a3d9551b6e27a5e3d3 as Dart was fixed in 76e86f35ef916091631268f2778d865a0ecb3fa3.

Re-enable Dart in CI; refs #1151

---

dmoj/cptbox/isolate.py
dmoj/executors/OBJC.py

* This executor calls `prctl` with 23.
* This executor tries to traverse `~/GNUstep`, but this directory doesn't exist. I did `RecursiveDir('~')` to work around this issue.
* Apparently, `initialize(cls)` doesn't run. I wrote `autoconfig(cls)` to do the setup.
* Afterwards, add `apt-get install make gnustep-devel` to the DMOJ dockerfile.

executors/OBJC: fix executor

---

README.md
dmoj/executors/NODEJS.py

Thanks again for maintaining DMOJ! It's a great project with a really solid security foundation.
We wanted to use DMOJ for internal company events, and since our company's primary language is Javascript (using Node.js), we wanted to implement a version that used Node directly rather than using https://github.com/DMOJ/v8dmoj
This resolves issue https://github.com/DMOJ/judge-server/issues/1136
- Add a judge executor that will execute code written in Node.js
- This was based on the Coffeescript executor, except with some newer syscalls added (e.g., io_uring)
- https://github.com/DMOJ/runtimes-docker/pull/71: Update Dockerfile to install Node.js to tier3 runtime image
Deployed a judge server with this with the following Dockerfile:
```sh
FROM dmoj/runtimes-tier3
RUN apt-get install -y …
```

Add Node.js executor for DMOJ

---

dmoj/executors/NODEJS.py

We already allow `pkey_alloc`.

executors/NODEJS: allow `pkey_free`

---

dmoj/executors/GO.py
dmoj/executors/base_executor.py

Since both Java and Go ask for them, seems reasonable to give everyone access.

executors: globally allow THP sysfs entries

---

dmoj/executors/RKT.py
dmoj/executors/compiled_executor.py
dmoj/executors/mono_executor.py

This makes sense because compilers are often written in the same language that they implement, so need similar whitelists.
This change enables Java 22 to compile.

executors: make compiler fs whitelists a superset of their runtimes'

---

testsuite/check_memory_limit/checker.py
testsuite/check_memory_limit/tests/c_blank/test.yml
testsuite/check_memory_limit/tests/cpp_too_much_memory/bloat.cpp
testsuite/check_memory_limit/tests/cpp_too_much_memory/test.yml

FreeBSD memory accounting is not very accurate - increasing the memory usage should make this test more robust.

tests/check_memory_limit: increase memory usage

---

dmoj/executors/asm_executor.py

See https://github.com/DMOJ/judge-server/actions/runs/10466584470/job/28983707605
(https://github.com/mcpt/wlmoj-judge/actions/runs/10975887920/job/30476034151) for a successful run

judge: fix the mypy error in CI

---

dmoj/executors/SBCL.py

the latest version of sbcl is more bloated
before:
```
0.972 Testing SBCL:   os_alloc_gc_space(1,0xb7ffb00000,173015040) failed with ENOMEM                                                                                                                       
1.032 fatal error encountered in SBCL pid 14 tid 14:                                                                                                                                                       
1.033 Can't allocate 0xa500000 bytes for space 5
1.033 
1.034 Failed self-test
1.035   Attempted:
1.036     sbcl: /usr/bin/sbcl
1.036   Errors:
1.037     Got unexpected stdout output:
1.037     
1.037 
1.038 Configuration result:
1.039 runtime: {}
```
after:
```
1.297 Testing SBCL:   Using /usr/bin/sbcl …
```

executors/sbcl: increase memory limit

---

dmoj/executors/BF.py

bf is broken due to
```
dmoj.error.CompileError: LLVM ERROR: Instruction Combining did not reach a fixpoint after 1 iterations
```
use the `instcombine<no-verify-fixpoint>` trick from https://github.com/llvm/llvm-project/issues/92648 to suppress this error
```
0.929 Testing BF:     Success                                                                                                                                                                              
1.201   opt: 19.1.6                                                                                                                                                                                        
1.214   llc: 19.1.6 …
```

executors/bf: suppress instcombine error for llvm >=18

---

dmoj/executors/GO.py

need these syscalls to upgrade go 1.22.5 to go 1.23.4
go took 6 seconds according to these logs
```
Sat, 21 Dec 2024 21:30:42 GMT    Testing GASARM: Unable to natively debug
Sat, 21 Dec 2024 21:30:48 GMT    Testing GO:     Using /usr/bin/go
Sat, 21 Dec 2024 21:30:48 GMT      go: 1.23.4
```

executors/go: allow new compiler syscalls

---

.github/workflows/build.yml

the most important one is `actions/cache`
https://github.blog/changelog/2024-12-05-notice-of-upcoming-releases-and-breaking-changes-for-github-actions/#actions-cache-v1-v2-and-actions-toolkit-cache-package-closing-down

ci: update workflow versions

---

dmoj/executors/RKT.py

Hopefully will finally fix the arm64 runtimes-docker build.

Bump RKT compiler time limit to 20 seconds

---

dmoj/checkers/bridged.py
dmoj/cptbox/_cptbox.pyi
dmoj/cptbox/_cptbox.pyx
dmoj/cptbox/helper.cpp
dmoj/cptbox/helper.h
dmoj/cptbox/isolate.py
dmoj/cptbox/lazy_bytes.py
dmoj/cptbox/utils.py
dmoj/executors/base_executor.py
dmoj/executors/shell_executor.py
dmoj/graders/bridged.py
dmoj/graders/interactive.py
dmoj/graders/standard.py
dmoj/problem.py
dmoj/tests/test_normalize.py
dmoj/utils/normalize.py
testsuite/shortest1/shortest1.py

Breaking changes:
* All interactors using `_interact_with_process`
This closes #835.

Switching to using memfd for input data

---

dmoj/executors/GO.py

Adding eventfd2 syscall, apparently used in Go from 1.23 https://github.com/golang/go/issues/65443 
I'm currently unable to submit Go code to judge due to 'RTE (eventfd2 syscall disallowed)'

GO: Adding eventfd2 syscall.
